name: Tag CI
on:
  release:
    types: [published, edited]
jobs:
  latest:
    name: Update latest tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Move latest tag
        run: |
          git tag -f latest ${{ github.event.release.tag_name }}
          git push -f origin latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}